### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by JPedroPeralta** [zq99/openai-vba-framework#1]
Hello,

Right after following the steps for installing, and running the tests included in the package, the code stops at a "debug.assert" and nothing is really happening. The interaction with OpenAI is working as I can see in the debug window that the response object is well populated (namely answering to the question of "capital of France"). Any thoughts?

**Comment by zq99** [comment]
There were some recent breaking changes to the OpenAI API, I think the json that is returned from the API has changed. So the VBA code needs to change to parse the information out from the json correctly when it is returned. The code at that the moment is trying to do this and populate the VBA response object and is not allocating the correct info to each property. I will take a look in more detail when I have some free time this week.

**Comment by zq99** [comment]
The code has been updated and is working fine for me. Please test when you get a chance. Thanks.
